;;; fff-consult-test.el --- Behavior tests for fff-consult.el -*- lexical-binding: t; -*-
(require 'cl-lib)
(add-to-list 'load-path default-directory)
(setq fff-core-file (expand-file-name "fff-core.so" default-directory))
(require 'fff)

(if (not (require 'consult nil t))
    (message "SKIP consult tests (consult not loadable)")
  (require 'fff-consult)

  ;; Tags round-trip.
  (let ((tagged (fff-consult--tag-input "hello" 'regex)))
    (unless (equal (fff-consult--strip-query-tags tagged) "hello")
      (error "tag strip failed: %S" tagged)))
  (let ((tagged (fff-consult--more-tag-input "hello" 2)))
    (unless (and (= (fff-consult--more-tag-n tagged) 2)
                 (equal (fff-consult--strip-query-tags tagged) "hello"))
      (error "more tag failed: %S" tagged)))

  (defvar fff-consult-test--root (expand-file-name "test-fixture" default-directory))

  (let ((root fff-consult-test--root))
    (make-directory root t)
    (with-temp-file (expand-file-name "hello.el" root)
      (insert ";;; hello.el\n(defun hello-greet ()\n  (message \"hello world\"))\n"))
    (with-temp-file (expand-file-name "notes.txt" root)
      (insert "hello from notes\nsecond line here\n"))
    (with-temp-file (expand-file-name "shout.txt" root)
      (insert "KABOOM LOUD\nsecond line here\n"))
    (with-temp-file (expand-file-name "export-many.txt" root)
      (dotimes (i 30)
        (insert (format "exportmark %d\n" i))))
    (let ((subdir (expand-file-name "subdir-alpha" root)))
      (make-directory subdir t)
      (with-temp-file (expand-file-name "keep.txt" subdir)
        (insert "dir marker\n")))
    (let ((id (fff--session root)))
      (unless (fff--wait-for-scan id 10000)
        (error "scan timed out"))
      ;; Dir fetch shared with vanilla.
      (unless (member "subdir-alpha/" (fff--dir-fetch id "subdir"))
        (error "consult dir fetch missed subdir"))
      ;; Format + consult position (preview/jump).
      (let* ((raw (car (fff--grep id "hello" "literal" 10 nil 0 1)))
             (cand (fff-consult--format-match raw '("hello"))))
        (unless (string-prefix-p "hello.el:1:" cand)
          (error "bad shape: %S" cand))
        (unless (eq (get-text-property 0 'face cand) 'consult-file)
          (error "missing consult-file face"))
        (let ((default-directory (file-name-as-directory root)))
          (unless (consp (consult--grep-position cand))
            (error "consult--grep-position failed"))))
      ;; Column round-trip.
      (let* ((raw (mapconcat #'identity
                             '("hello.el" "1" "4" ";;; hello.el" "4-9") fff--sep))
             (cand (fff-consult--format-match raw '("hello") 'regex)))
        (unless (equal (substring-no-properties cand) "hello.el:1:5:;;; hello.el")
          (error "consult lost the column: %S" cand))
        (let ((default-directory (file-name-as-directory root)))
          (let ((pos (consult--grep-position cand)))
            (with-current-buffer (marker-buffer (car pos))
              (save-excursion
                (goto-char (car pos))
                (unless (and (= (line-number-at-pos) 1) (= (current-column) 4))
                  (error "consult jump missed column")))))))
      ;; Session fetch: tagged input equals plain; smart on/off.
      (let ((cell (list 'literal)) (state (fff-consult--make-paging-state)))
        (unless (equal (fff-consult--fetch id "hello" cell state)
                       (fff-consult--fetch id (fff-consult--tag-input "hello" 'regex) cell state))
          (error "tagged fetch differs")))
      (let ((cell (list 'literal)) (state (fff-consult--make-paging-state)))
        (let ((on (fff-consult--fetch id "kaboom" cell state (list t)))
              (off (fff-consult--fetch id "kaboom" cell (fff-consult--make-paging-state) (list nil))))
          (unless (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) on)
            (error "session smart on missed KABOOM"))
          (when (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) off)
            (error "session smart off leaked KABOOM"))))
      ;; Paging grows and drains to the one-shot result.
      (let* ((cell (list 'literal)) (state (fff-consult--make-paging-state))
             (fff-grep-page-size 1)
             (p1 (fff-consult--fetch id "hello" cell state)))
        (unless (and (consp p1) (> (aref state fff-consult--st-offset) 0))
          (error "expected a second page"))
        (let ((p2 (fff-consult--fetch id (fff-consult--more-tag-input "hello" 1) cell state)))
          (unless (> (length p2) (length p1))
            (error "second page did not grow"))))
      ;; Load-more pushes; quiet when done or outside a session.
      (let ((pushed nil) (state (vector "hello" '("m") 7 nil nil 0)))
        (with-temp-buffer
          (setq-local fff-consult--push (lambda (input) (setq pushed input) nil))
          (setq-local fff-consult--paging-state state)
          (unless (fff-consult--load-more) (error "load-more should start"))
          (unless (equal pushed (fff-consult--more-tag-input "hello" 1))
            (error "load-more pushed wrong input: %S" pushed))))
      (when (fff-consult--scroll-load-more (selected-window) 1)
        (error "scroll hook should stay quiet outside a session"))
      (message "SMOKE-CONSULT OK")))

  ;; Export when embark is around.
  (when (and (require 'embark nil t) (require 'embark-consult nil t))
    (let* ((root fff-consult-test--root)
           (id (fff--session root)))
      (unless (fff--wait-for-scan id 10000)
        (error "scan timed out"))
      (let ((cands (mapcar (lambda (raw) (fff-consult--format-match raw '("hello")))
                           (fff--grep id "hello" "literal" 10 nil 0 1))))
        (embark-consult-export-grep cands)
        (let ((buf (get-buffer "*Embark Export Grep*")))
          (unless (and buf (buffer-live-p buf)) (error "export buffer missing"))
          (with-current-buffer buf
            (unless (derived-mode-p 'grep-mode) (error "export not in grep-mode")))
          (kill-buffer buf)
          (message "SMOKE-CONSULT export OK"))))))
;;; fff-consult-test.el ends here
