;;; fff-test.el --- Behavior tests for fff.el -*- lexical-binding: t; -*-
(require 'cl-lib)
(add-to-list 'load-path default-directory)
(setq fff-core-file (expand-file-name "fff-core.so" default-directory))
(require 'fff)

(setq fff-frecency-db-path (make-temp-file "fff-test-frecency-" t)
      fff-history-db-path (make-temp-file "fff-test-history-" t))

(defvar fff-test--root (expand-file-name "test-fixture" default-directory))

(let ((root fff-test--root))
  (make-directory root t)
  (with-temp-file (expand-file-name "hello.el" root)
    (insert ";;; hello.el\n(defun hello-greet ()\n  (message \"hello world\"))\n"))
  (with-temp-file (expand-file-name "notes.txt" root)
    (insert "hello from notes\nsecond line here\ntag !exclude-me done\nsee /src/ here\n"))
  (with-temp-file (expand-file-name "game.c" root)
    (insert "/* game.c */\nint main(void){return 0;}\n"))
  (with-temp-file (expand-file-name "say_hllo.txt" root)
    (insert "decoy\n"))
  (with-temp-file (expand-file-name "shout.txt" root)
    (insert "KABOOM LOUD\nsecond line here\n"))
  (with-temp-file (expand-file-name "many.txt" root)
    (dotimes (i 150)
      (insert (format "capmark %d\n" i))))
  (let ((subdir (expand-file-name "subdir-alpha" root)))
    (make-directory subdir t)
    (with-temp-file (expand-file-name "keep.txt" subdir)
      (insert "dir marker\n")))
  (let ((id (fff--session root)))
    (unless (fff--wait-for-scan id 10000)
      (error "scan timed out"))
    (message "SMOKE file-count=%s" (fff--file-count id))
    ;; Scan done.
    (let ((st (fff--scan-progress id)))
      (unless (and (consp st) (natnump (car st)) (not (nth 1 st)))
        (error "scan should be done: %S" st)))
    ;; DBs configured.
    (let ((st (fff--db-status id)))
      (unless (and (= (length st) 2)
                   (string-match-p (regexp-quote fff-frecency-db-path) (nth 0 st)))
        (error "db-status wrong: %S" st)))
    ;; File search, incl. typos.
    (unless (member "hello.el" (fff--file-fetch id "hello"))
      (error "file-fetch missed hello.el"))
    (unless (member "hello.el" (fff--file-fetch id "hllo"))
      (error "typo search missed hello.el"))
    (unless (member "game.c" (fff--file-fetch id "gaem"))
      (error "typo search missed game.c"))
    ;; Dir search.
    (let ((dirs (fff--dir-fetch id "subdir")))
      (unless (member "subdir-alpha/" dirs)
        (error "dir-fetch missed subdir-alpha/: %S" dirs)))
    ;; Tracking lands in the DBs.
    (let ((abs (expand-file-name "hello.el" root)))
      (unless (fff--track-access id abs)
        (error "track-access missed the DB"))
      (unless (fff--track-query-completion id "hllo" abs)
        (error "track-query-completion missed the DB")))
    ;; Git + health smoke.
    (unless (natnump (fff--refresh-git-status id))
      (error "git refresh did not return a count"))
    ;; Grep: hits, multi-term, exclusion.
    (unless (fff--grep id "hello" "literal" 10 nil 0 1)
      (error "grep returned no hits"))
    (unless (fff--grep id "hello world" "literal" 10 nil 0 1)
      (error "multi-term grep returned no hits"))
    (let ((parsed (fff--grep id "hello !notes" "literal" 20 nil 0 1)))
      (unless (and parsed
                   (not (seq-some (lambda (m) (string-prefix-p "notes.txt" m)) parsed)))
        (error "parsed grep should exclude notes.txt: %S" parsed)))
    (when (fff--grep-raw id "hello !notes" "literal" 20 nil 1)
      (error "raw grep should take !notes literally"))
    ;; Format: shape, props, face, column.
    (let* ((raw (car (fff--grep id "hello" "literal" 10 nil 0 1)))
           (cand (fff--plain-format-match raw '("hello"))))
      (unless (string-prefix-p "hello.el:1:" cand)
        (error "bad candidate shape: %S" cand))
      (unless (equal (get-text-property 0 'fff--file cand) "hello.el")
        (error "missing fff--file prop"))
      (with-temp-buffer
        (insert cand)
        (goto-char (point-min))
        (unless (text-property-search-forward 'face 'match t)
          (error "missing match face"))))
    ;; Wire parse: col + ranges, separator in content.
    (pcase-let ((`(,file ,line ,content ,col ,ranges)
                 (fff--parse-raw-match
                  (mapconcat #'identity '("f.el" "12" "4" "hello" "0-5") fff--sep))))
      (unless (and (equal file "f.el") (equal col "5") (equal ranges '((0 . 5))))
        (error "parse dropped col/ranges: %S" (list file line content col ranges))))
    (let ((cand (fff--plain-format-match
                 (mapconcat #'identity '("f.el" "3" "4" "say hello" "4-9") fff--sep)
                 '("hello") 'regex)))
      (unless (equal (substring-no-properties cand) "f.el:3:5:say hello")
        (error "plain shape lost the column: %S" cand)))
    ;; grep-mode entry.
    (unless (string-match (car fff--grep-error-regexp) "hello.el:1:5:x")
      (error "grep entry cannot parse file:line:col:"))
    (with-temp-buffer
      (grep-mode)
      (fff--grep-buffer-setup)
      (unless (= compilation-first-column 1)
        (error "grep buffer columns wrong")))
    ;; Per-file cap: capped fetch keeps 2, unlimited gets 150.
    (let ((fff-max-matches-per-file 2))
      (let ((capped (fff--grep-fetch id "capmark" 'literal))
            (full (fff--grep-fetch id "capmark" 'literal t)))
        (unless (and (= (length capped) 2) (= (length full) 150))
          (error "cap not honored: %s vs %s" (length capped) (length full)))))
    ;; Smart-case through one entry point + fetch.
    (let ((on (fff--grep-ex id "kaboom" "literal" 20 0 0 (fff--file-size-arg) 0 0 1))
          (off (fff--grep-ex id "kaboom" "literal" 20 0 0 (fff--file-size-arg) 0 0 0)))
      (unless (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) on)
        (error "smart on missed KABOOM: %S" on))
      (when (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) off)
        (error "smart off leaked KABOOM: %S" off)))
    (let ((on (fff--grep-fetch id "kaboom" 'literal nil 1))
          (off (fff--grep-fetch id "kaboom" 'literal nil 0)))
      (unless (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) on)
        (error "fetch smart on missed KABOOM"))
      (when (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) off)
        (error "fetch smart off leaked KABOOM")))
    ;; Uppercase stays sensitive.
    (let ((hits (fff--grep-ex id "KABOOM" "literal" 20 0 0 (fff--file-size-arg) 0 0 0)))
      (unless (seq-some (lambda (m) (string-prefix-p "shout.txt" m)) hits)
        (error "uppercase query missed shout.txt")))
    ;; Filename constraint: off literal, on scopes to file.
    (let ((off (fff--grep-ex id "greet hello.el" "literal" 20 0
                             0 (fff--file-size-arg) 0 0 1))
          (on (fff--grep-ex id "greet hello.el" "literal" 20 0
                            0 (fff--file-size-arg) 0 1 1)))
      (when off
        (error "constraint off should find nothing literally: %S" off))
      (unless (and on (seq-every-p (lambda (m) (string-prefix-p "hello.el" m)) on))
        (error "constraint on should scope to hello.el: %S" on)))
    (let ((fff-grep-filename-constraint t))
      (when (fff--grep-raw id "greet hello.el" "literal" 20 nil 1)
        (error "raw must stay verbatim"))
      (unless (equal (fff--literal-terms "hello hello.el") '("hello"))
        (error "terms kept the file filter")))
    ;; Paging: union equals one-shot.
    (let* ((one (fff--grep-ex id "hello" "literal" 2000 0 0 (fff--file-size-arg) 0 0 1))
           (seen nil) (offset 0) (done nil) (pages 0))
      (while (not done)
        (setq pages (1+ pages))
        (when (> pages 50) (error "paging did not terminate"))
        (let ((page (fff--grep-page id "hello" "literal" 1 0
                                    0 (fff--file-size-arg) 0 0 offset 1)))
          (setq seen (append seen (cdr page)) offset (car page))
          (when (= offset 0) (setq done t))))
      (unless (equal (sort (copy-sequence seen) #'string<)
                     (sort (copy-sequence one) #'string<))
        (error "paged union differs")))
    ;; Min-input guard.
    (let ((fff-min-grep-input 2))
      (when (fff--grep-fetch id "h" 'literal)
        (error "fetch below min input returned candidates")))
    ;; Selectable guards.
    (unless (equal (fff--selectable-file "hello.el" root)
                   (expand-file-name "hello.el" root))
      (error "selectable missed a file"))
    (when (fff--selectable-file "nope-missing.el" root)
      (error "selectable accepted a missing file"))
    (unless (equal (fff--selectable-dir "subdir-alpha/" root)
                   (expand-file-name "subdir-alpha/" root))
      (error "selectable-dir missed a dir"))
    (when (fff--selectable-dir "hello.el" root)
      (error "selectable-dir accepted a file"))
    ;; Tables use file category; typo hits survive.
    (let* ((table (fff--file-completion-table id))
           (md (completion-metadata "" table nil)))
      (unless (eq (completion-metadata-get md 'category) 'file)
        (error "file table missing category")))
    (let* ((table (fff--file-completion-table id))
           (completion-styles-alist (cons fff--file-completion-style completion-styles-alist))
           (completion-styles '(fff-files))
           (cands (completion-all-completions "hllo" table nil 4 nil)))
      (unless (member "hello.el" cands)
        (error "passthrough dropped typo hit: %S" cands)))
    ;; Modes fail loudly.
    (condition-case nil
        (progn (fff--normalize-grep-mode 'plain) (error "plain accepted"))
      (user-error nil))
    (unless (and (eq (fff--next-grep-mode 'literal) 'regex)
                 (eq (fff--next-grep-mode 'regex) 'fuzzy)
                 (eq (fff--next-grep-mode 'fuzzy) 'literal))
      (error "mode cycle broke"))
    ;; Clear + re-init.
    (let ((deleted (fff--clear-caches id)))
      (unless (= (length deleted) 2)
        (error "clear should remove two DB dirs: %S" deleted)))
    (remhash root fff--sessions)
    (let ((id2 (fff--session root)))
      (unless (fff--wait-for-scan id2 10000)
        (error "re-init scan timed out"))
      (unless (member "hello.el" (fff--search id2 "hello" 10 (fff--max-threads-arg)))
        (error "re-init search failed")))
    (message "SMOKE OK")))
;;; fff-test.el ends here
